a=int(input("enter first number"))
b=int(input("enter second number"))
print("sum:",a+b)
print("difference:",a-b)
print("product:",a*b)
print("quotient:",a/b)
print("remainder:",a%b)
print("floor division:",a//b)